# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Office E5

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1,2,8,12 */2 * *' # 每2天 9，10，16，20点各执行一次（东八区，UTC+8）
  release:
    types: [published]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn install -Dmaven.test.skip=true
    - name: Run jar
      env:
        E5_CLIENT_ID: ${{ secrets.E5_CLIENT_ID }}
        E5_CLIENT_SECRET: ${{ secrets.E5_CLIENT_SECRET }}
        E5_TENANT_GUID: ${{ secrets.E5_TENANT_GUID }}
        E5_USERNAME: ${{ secrets.E5_USERNAME }}
        E5_PASSWORD: ${{ secrets.E5_PASSWORD }}
      run: |
        java -jar ./target/officeE5-1.0-SNAPSHOT-jar-with-dependencies.jar "$E5_CLIENT_ID" "$E5_USERNAME" "$E5_PASSWORD" "$E5_TENANT_GUID" "$E5_CLIENT_SECRET"  >> ./run.log
        tail run.log
